### PR TITLE
Dpikt/registration backend

### PR DESCRIPTION
**Pull request by dpikt**
New login responses and registration API calls

### CODE REVIEW

**Comment by JSlote** [comment]
@taoduo I'm thinking it would be better if you verified this PR you're working directly on this stuff. If you'd like me to instead, just let me know! We're trying to get things done by the end of this week!

**Comment by taoduo** [comment]
@dpikt @JSlote 
I read the code, although I have not run it yet. Everything looks great. I think user verification / password reset / verification link resend will all work on the backend now. Am I right?

I only have one question. Do we update our registration backend here? I think according to #30, when an unverified email is trying to register, we will overwrite the original record but now I think it might return a mongo error.

I will pull the code tonight and run it to further verify everything is working but we do not have wait until tonight to merge, if we do not plan to update the registration backend on this pull request.

**Comment by dpikt** [comment]
Correct on all counts @taoduo! I'm gonna try to do the registration backend stuff tomorrow, it makes sense to add that stuff before we merge instead of starting a new PR for that. I'll keep you posted.

**Comment by dpikt** [comment]
Ok @taoduo all the registration cases should be working correctly now!

**Comment by JSlote** [comment]
@taoduo how do things look now?

**Comment by taoduo** [comment]
@JSlote I checked the other one just now. It works well and I think it is ready to merge. I am going to try this one now.

**Comment by taoduo** [comment]
@JSlote @dpikt I ran it. It mostly works well. I just have one question and one comment:
1. Resetting password gives a new random password. How can the users set the password to another one that they want?
2. Just a comment. When an unverified user wants to reset the password, the email is sent but the link does not work. It just says "not user found by this condition".

**Comment by JSlote** [comment]
@taoduo Thanks for checking it out! Let me take a stab at answering your qs:

1) Once @dpikt implements a password changing call, I'll add a password change field in the user page view (which is currently being devved on #42) so the users should be able to set their password by going to their user page.
2) That is a problem! Thanks for catching it. @dpikt I forget what we decided here...we weren't allowing unverified users to reset their passwords, were we?

**Comment by dpikt** [comment]
Yeah that's a mistake. Just a sec

**Comment by dpikt** [comment]
That should be fine for now, @taoduo can you verify that this works?

**Comment by taoduo** [comment]
This should work but I messed up my git repository. It takes a while to get fixed. You guys can verify it and merge it.

**Comment by dpikt** [comment]
Ok. There's another PR on the way, so be warned O_o

**Pull request merged**
