### PR TITLE
removed email case-sensitivity

### PR DESCRIPTION
**Pull request by taoduo**
Login email is no longer case sensitive;
Register email is no longer case sensitive.

### CODE REVIEW

**Comment by JSlote** [comment]
Thanks Duo! I'll check it out right now.

**Comment by JSlote** [comment]
Hey @taoduo, I think what you've done works well for the login, but it would be great if we could catch uppercase stuff on registration, password reset, etc. etc.

A different coding pattern you might think about pursuing is making a new set of middleware called *normalizers* (putting them in `normalizers.js` like injectors are in `injectors.js`). These middleware would normalize requests so that we wouldn't have to code each database lookup and other internal function so defensively. I'm thinking you'd write one normalizer called lowercaseEmail or something that checks if `req` has a `username` property and if so does `username = username.toLowerCase()`. Does that make sense?

**Comment by taoduo** [comment]
@JSlote I agree. I will get the middleware and put it in all places.

**Comment by dpikt** [comment]
Suggestion- instead of adding it to routes individually, you can make it run on every request using app.use() in server.js

**Comment by taoduo** [comment]
@dpikt Ok, I get it.

**Comment by taoduo** [comment]
That was an accidental push. I removed it. Now I think it works.

**Pull request merged**
