### PR TITLE
Dpikt/error handling

### PR DESCRIPTION
**Pull request by dpikt**
This is all just refactoring to use the recommended style for handling errors in Express...
EXCEPT for the /resendVerification call, which I changed a little bit. You can see the change in the API spec.

### CODE REVIEW

**Comment by dpikt** [comment]
There's a little bit too much here for one person the look over, and there's no need really. The only important change is the API call change, so just have a look at that.

**Comment by dpikt** [comment]
@taoduo can you edit the frontend to play nicely with the change to /resendVerification?

**Comment by taoduo** [comment]
@dpikt Sure. How do we usually make changes like this? I guess this does not need a new pull reuqe

**Comment by taoduo** [comment]
@dpikt Done.

**Pull request merged**
