### PR TITLE
Jslote/user view -- second round of checking

### PR DESCRIPTION
**Pull request by JSlote**
This is just a preparatory PR so I have something to reference in issues.

### CODE REVIEW

**Comment by JSlote** [comment]
I humbly submit my PR as ready

**Comment by dpikt** [comment]
Do you want styling feedback or am I just checking functionality?

**Comment by JSlote** [comment]
@dpikt I would love styling feedback, but functionality is the main goal of this particular PR. I have to do some final styling for the beta (most importantly, the login/signup stuff). Maybe you could put the styling feedback in an issue?

**Comment by dpikt** [comment]
@JSlote Ok I'll try to separate nitpicky things from things that are actually important! Here are some things I've noticed so far:
- The email settings and password settings are visible all the time, not just when the edit button is clicked
- Changing your name doesn't change it in the top bar thing (this may be too annoying to bother fixing)
- The avatar crop view should appear after a picture is selected
- The watchlist isn't centered when it's empty
- Watchlists don't have any info except for name and picture (maybe you changed your mind on this)
- Bio is limited to a single line
- Putting in an invalid value for name leads to some weird behavior
- Password format suggestions are unhelpful ("please match the requested format")
- I'm not sure if the books on offer bit is necessary. I also keep wanting to click on it.
- Could we change it to "Email me when:" and "Change my password:" (ok maybe this one is nitpicky)
- Can we indicate that there's a length limit for the bio when the edit button is clicked?

**Comment by dpikt** [comment]
Also ps your changes are dope

**Comment by JSlote** [comment]
Let me respond to a couple:

1. Yea, intentional. The issue is that the "confirm" button only updates the bio, name, and grad year and I thought it would be confusing to have nested confirm/submit buttons that only confirm/submit parts of the thing that get revealed. What do you think?
2. Nice catch! That should be easy to fix. Lemme go ahead and change that. **I'll add this to this PR**
3. **I'm confused by this.** What's the crop view?
5. Adding more info will require a non-trivial modification of the way the server responds to the get watchlist query. In particular, it would have to books into the list and then, if I understand it, also count listings per book. I didn't feel like I was up to the task of doing this at the moment--if you think you could do it tomorrow that would be awesome, but I would understand if you can't
6. **Weird. I can't reproduce**. What's wrong with this?
image
7. Thanks for the catch. **I'll also add this to this PR**
8. But it says at least 5 characters.
9. I could make it scroll you down on click?
10. Ugh fine
11. Yea, sure. **I'll add this to the PR**

**Comment by dpikt** [comment]
Cool, here are thoughts: 

1. I think the potential confusion is outweighed by having them clutter up the user page... worst case scenario they'll click the top confirm button unnecessarily.

3. The crop view is this doodad: 
screen shot 2016-08-09 at 12 28 12 am

5. I thought that might be the case. We can forget it for now I think.

6. Definitely different for me! 
screen shot 2016-08-09 at 12 25 37 am

8. I know, but there are also some other guidelines that aren't listed (no special characters, etc). It might be more consistent to let the backend do all of the validation and return better messages seeing as the default message is so vague.

9. I'm against auto-scrolling on principle.

10. Good

**Comment by JSlote** [comment]
1. But what if they then think their password is changed when it really isn't?
2. Oh gotcha. I can hide that, sure.
4. You didn't put any spaces in your text! I can set the browser to break up words, but that isn't default nearly anywhere on the nets.
5. I guess I could remove validation. Is it ok if I keep it on the retype part? I have control over the message there and it's not actually sent to the backend anyway.

**Comment by dpikt** [comment]
1. I think "submit" is pretty clear
3. Lol the more you know
4. Yeah you should keep the retype part

**Comment by JSlote** [comment]
Todo list:

- [ ] Also change nav bar name on user page name change (2)
- [ ] Hide crop view until a picture is loaded
- [ ] Keep the watchlist centered when empty
- [ ] Fix weird behavior on invalid name input
- [ ] Consider changing validation on the password form
- [ ] Change to "email me when:" and "update my password:"
- [ ] Indicate length limit on bio

**Comment by dpikt** [comment]
We've got some unused views, wanna delete those while you're at it?

**Comment by JSlote** [comment]
Like what?

**Comment by JSlote** [comment]
Oh nvm, got it.

**Comment by JSlote** [comment]
@dpikt Alright I think it's ready for your perusal again

**Comment by dpikt** [comment]
Perusal mode engaged

**Comment by dpikt** [comment]
- The character count on the bio field is fun, good job
- If we're gonna keep the "books offered" thing we should put it under class year- I'm not a fan of the pipe
- What do you think of making the name fields gray like the bio field instead of underlining them?
- I think "update info" should close out of the editing view, even if it means them having to click the edit button again to change their password
- If you enter nothing for your name and click "submit" there's no indication that it didn't work (I'll fix this actually, just a sec)

**Comment by dpikt** [comment]
Fixed 5

**Comment by dpikt** [comment]
I'm appeased.... for now!
MERGE

**Pull request merged**
