### PR TITLE
Contact popup

### PR DESCRIPTION
**Pull request by taoduo**
**Finished the contact popup window frontend**
## Changes
1. Added the contact modal to app/views/modals.jade
2. Added code to popup the contact modal when
 * 404 error happens (app/views/partials/detail.error.jade)
 * "Did not find what you get?" button click (app/views/partials/search.jade)
3. Moved modalStates variable to rootScope (public/scripts/main.js)
4. Created dummy backend (app/routes.js)

### CODE REVIEW

**Comment by dpikt** [comment]
Nice work! I'll fill in the backend route tomorrow and we can talk about handling the possible responses that it'll send.

**Comment by dpikt** [comment]
Ok, I just made some changes to the backend. It still doesn't do everything I'm planning on making it do, but it does send predictable responses. Now it's up to you to handle those responses on the frontend.

Here's what I'm thinking: There are two possible responses the route can send, a 200 or a 400 (to get the 400, try sending a report with no message). Once the user clicks submit on the frontend, you should wait to receive the response and then...
- If it's a 200, close the popup, and maybe display a success message
- If it's a 400, display the error message that's returned

This will require moving some logic into the angular file, which is somewhat daunting. If you've got questions about that, ask @JSlote. You'll want to wrap the route in the api module, and call it from the main file.

**Comment by JSlote** [comment]
Hey Duo, this looks pretty good. You've done a wonderful job of integrating the popup into the current architecture. The one thing is that there's another potential error state, where someone looses connection to the internet before they submit the form. Currently nothing happens, but I think we need something there. What's the idiom for this situation? Besides that little thing, I think the PR is ready.

**Comment by taoduo** [comment]
I don't know the idiom. I checked the http status code definitions and I did not find anything related. I am afraid it is not an http error. But I find there is something built in javascript to check if the user is online:
`navigator.onLine`, a boolean that represents the connection status.
I checked that before handling form submission to alert the user when the user is offline.
Checking online/offline might also be necessary elsewhere. How did we handle it at other places?

**Comment by JSlote** [comment]
We are not currently handling it at other places, so I think we should call the PR done and make a new new issue to deal with loss of connection.

**Pull request merged**
