### PR TITLE
Dpikt/navbuttons

### PR DESCRIPTION
**Pull request by JSlote**
this is better

### CODE REVIEW

**Comment by dpikt** [comment]
Would it be a pain in the ass to make the back button stay in place as you scroll up and down the page?

**Comment by dpikt** [comment]
Another suggestion: make the clickable area of the button larger than just the character

**Comment by JSlote** [comment]
How about this? I would fix the transition too but I can't figure out what is adding "display:none" to it when you click away

**Comment by dpikt** [comment]
Looks great!

**Pull request merged**
